// Voro++, a 3D cell-based Voronoi library
//
// Author   : Chris H. Rycroft (LBL / UC Berkeley)
// Email    : chr@alum.mit.edu
// Date     : July 1st 2008

/** \file worklist.hh
 * \brief Header file for setting constants used in the block worklists that are
 * used during cell computation.
 *
 * This file is automatically generated by worklist_generate.pl and it is not
 * intended to be edited by hand. */

static const int hgrid=4;
static const int fgrid=8;
static const int hgridsq=64;
static const int seq_length=64;
static const unsigned int wl[4096];
