// Voronoi calculation code
//
// Author   : Chris H. Rycroft (LBL / UC Berkeley)
// Email    : chr@alum.mit.edu
// Date     : July 1st 2008

/* This file is automatically generated by worklist_generate.pl */

static const int hgrid=4;
static const int fgrid=8;
static const int hgridsq=64;
static const int seq_length=64;
static const unsigned int wl[4096];
