// Voro++, a 3D cell-based Voronoi library
//
// Author   : Chris H. Rycroft (LBL / UC Berkeley)
// Email    : chr@alum.mit.edu
// Date     : May 18th 2011

/** \file worklist.hh
 * \brief Header file for setting constants used in the block worklists that are
 * used during cell computation.
 *
 * This file is automatically generated by worklist_gen.pl and it is not
 * intended to be edited by hand. */
 
/** Each region is divided into a grid of subregions, and a worklist is
# constructed for each. This parameter sets is set to half the number of
# subregions that the block is divided into. */
static const int hgrid=4;
/** The number of subregions that a block is subdivided into, which is twice
the value of hgrid. */
static const int fgrid=8;
/** The total number of worklists, set to the cube of hgrid. */
static const int hgridcu=64;
/** The number of elements in each worklist. */
static const int seq_length=64;
/** The pre-computed block worklists. */
static const unsigned int wl[4096];
